repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: run-blue
        name: Run Blue formatter
        entry: python run_blue.py
        language: system
        pass_filenames: false
        types: [python]
